#!/bin/bash

###################################

#
# BEGIN Load common
#

export OPENSHIFT_RUNTIME_DIR=${OPENSHIFT_DIY_DIR}/runtime/
export OPENSHIFT_RUN_DIR=${OPENSHIFT_DIY_DIR}/run/
export OPENSHIFT_BIN=${OPENSHIFT_RUNTIME_DIR}/bin/

export PATH=${OPENSHIFT_BIN}:$PATH

# When using rockmongo this is set and can cause strange errors here
export PHPRC=${OPENSHIFT_RUNTIME_DIR}/etc/php/

#
# END Load common
#

###################################

echo "Stopping nginx."
if [ -f ${OPENSHIFT_RUN_DIR}/nginx.pid ];then
    kill -QUIT `cat ${OPENSHIFT_RUN_DIR}/nginx.pid`
fi

echo "Stopping PHP-fpm."
if [ -f ${OPENSHIFT_RUN_DIR}/php-fpm.pid ];then
    kill -QUIT `cat ${OPENSHIFT_RUN_DIR}/php-fpm.pid`
fi

# Always succeed, otherwise OpenShift declines to run build and start
# hooks.
exit 0
